## 捕捉异常
```
public class Take { // 创建类
	public static void main(String[] args) {
		try { // try语句中包含可能出现异常的程序代码
			String str = "lili"; // 定义字符串变量
			System.out.println(str + "年龄是："); // 输出的信息
			int age = Integer.parseInt("20L"); // 数据类型转换
			System.out.println(age);
		} catch (Exception e) { // catch语句块用来获取异常信息
			e.printStackTrace(); // 输出异常性质
		}
		System.out.println("program over"); // 输出信息
	}
}

```
- finally语句块
#### 自定义异常
```
public class MyException extends Exception {//创建自定义异常，继承Exception类
	public MyException(String ErrorMessagr) { // 构造方法
		super(ErrorMessagr); // 父类构造方法
	}
}


public class Tran { // 创建类
	 // 定义方法，抛出异常
	static int avg(int number1, int number2) throws MyException {
		if (number1 < 0 || number2 < 0) { // 判断方法中参数是否满足指定条件
			throw new MyException("不可以使用负数"); // 错误信息
		}
		if (number1 > 100 || number2 > 100) { // 判断方法中参数是否满足指定条件
			throw new MyException("数值太大了"); // 错误信息
		}
		return (number1 + number2) / 2; // 将参数的平均值返回
	}
	
	public static void main(String[] args) { // 主方法
		try { // try代码块处理可能出现异常的代码
			int result = avg(102, 150); // 调用avg()方法
			System.out.println(result); // 将avg()方法的返回值输出
		} catch (MyException e) {
			System.out.println(e); // 输出异常信息
		}
	}
}

```
#### throw关键字异常
```
public class Shoot { // 创建类
	static void pop() throws NegativeArraySizeException {
		// 定义方法并抛出NegativeArraySizeException异常
		int[] arr = new int[-3]; // 创建数组
	}
	public static void main(String[] args) { // 主方法
		try { // try语句处理异常信息
			pop(); // 调用pop()方法
		} catch (NegativeArraySizeException e) {
			System.out.println("pop()方法抛出的异常");// 输出异常信息
		}
	}
}


public class MyException extends Exception { // 创建自定义异常类
	String message; // 定义String类型变量
	
	public MyException(String ErrorMessagr) { // 父类方法
		message = ErrorMessagr;
	}
	
	public String getMessage() { // 覆盖getMessage()方法
		return message;
	}
}


public class Captor { // 创建类
	static int quotient(int x, int y) throws MyException { // 定义方法抛出异常
		if (y < 0) { // 判断参数是否小于0
			throw new MyException("除数不能是负数"); // 异常信息
		}
		return x / y; // 返回值
	}
	
	public static void main(String args[]) { // 主方法
		try { // try语句包含可能发生异常的语句
			int result = quotient(3, -1); // 调用方法quotient()
		} catch (MyException e) { // 处理自定义异常
			System.out.println(e.getMessage()); // 输出异常信息
		} catch (ArithmeticException e) { // 处理ArithmeticException异常
			System.out.println("除数不能为0"); // 输出提示信息
		} catch (Exception e) { // 处理其他异常
			System.out.println("程序发生了其他的异常"); // 输出提示信息
		}
	}
}

```